update setup.py dependencies to resolve pypi conflicts
attempting to reconcile
```bash
ERROR: sphinx 3.5.4 has requirement docutils<0.17,>=0.12, but you'll have docutils 0.17.1 which is incompatible.
``` 
```bash
ERROR: tensorboard 2.9.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.20.1 which is incompatible.
```

pending test by @dhuangnm